### ISSUE TITLE
How insert, delete, retain work together?

### ISSUE THREAD

**Issue by gztchan** [quilljs/delta#12]
```js
var temp = new Delta([
  { insert: 'Gandalf', attributes: { bold: true } },
]).retain(1).delete(2).insert('text').delete(1).retain(2).insert('more').delete(2);
```

**Log**

![image](https://cloud.githubusercontent.com/assets/6322366/26048258/e64089d6-3988-11e7-897a-5d2ff969202a.png)

**Questions**
Why deletes after each retain is moved behind insert if insert is existed? It seems that the document about Delta does't state about this feature. Please help, thank you! 👍 

after I read following code in delta.js
```js
    // Since it does not matter if we insert before or after deleting at the same index,
    // always prefer to insert first
    if (typeof lastOp['delete'] === 'number' && newOp.insert != null) {
      index -= 1;
      lastOp = this.ops[index - 1];
      if (typeof lastOp !== 'object') {
        this.ops.unshift(newOp);
        return this;
      }
    }
```

Does it means that

"example"
1. retain(1), skip "e"
2. delete(1), remove "x",
3. insert("a"), insert "a" before "x"
4. output is "eaample"

"example"
1. retain(1), skip "e"
2. insert("a"), insert "a" before "x"
3. (retain(1) <- this not attended retain is merged into previous insert?)
3. delete(1), remove "x",
4. output is "eaample", same to the last case.

**Comment by jhchen** [comment]
All instructions in a Delta refers to the **current** document. If you had insert a, delete 1, it does not mean delete the a you just inserted. Therefore in your second example step 3 is not necessary and why the order of adjacent inserts and deletes do not matter. However since that creates ambiguity, we favor choose to always insert first.

I did write a [guide](https://quilljs.com/guides/designing-the-delta-format/) that explained some of the thinking behind designing deltas in Quill's documentation. However I did not link it in this project since it was not yet separate from [ottypes](https://github.com/ottypes/rich-text) but seems like it might be helpful to add now.
