### ISSUE TITLE
"fast-diff/diff has no default export" error

### ISSUE THREAD

**Issue by bogacg** [quilljs/delta#33]
I have an Angular app which started to give `"fast-diff/diff has no default export"` error upon build after I've updated my dependencies.  
I post it here because Error message begins with:

>ERROR in node_modules/@types/quill/node_modules/quill-delta/dist/Delta.d.ts(1,8):

Please check.

**UPDATE**
I removed **@types/quill** from dependencies, now I don't get error and build does not fail.

**Comment by boscohyun** [comment]
import diff from 'fast-diff';
->
import diff = require('fast-diff');

**Comment by wvyeun** [comment]
I have the same error when I try to 
```yarn add react-quill```

**Comment by sumitvekariya** [comment]
file: node_modules\fast-diff\diff.js (line number 774) **`export = diff`** to **`export default diff`**
file: node_modules\quill-delta\dist\Delta.js (line number 377) **`module.exports = Delta;`** to **`export default Delta`**

**Comment by dgreensp** [comment]
The simplest way to fix this issue is to set the compilerOption [`"esModuleInterop": true`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop) in your tsconfig.json.

The modules fast-diff and quill-delta are exported using `export =` because this is the only way they can be backwards-compatible with CommonJS require statements like `const diff = require('fast-diff')`.

Using Babel, you can then write `import diff from 'fast-diff'` because of Babel's module interop behavior.  TypeScript originally did not have this interop, forcing you to write `import diff = require('fast-diff')`, but this is ugly, and they changed their mind in 2.7 to be like Babel.  They put the new behavior behind a flag because it is breaking, but they "highly recommend" you use the new behavior.

We could change Delta.ts to say `import diff =`, but the point of TypeScript's change to module interop is that no one should have to type that anymore, so let me know if turning on the new module interop isn't a valid solution for you.

**Comment by dave0688** [comment]
@dgreensp What a nice answer, it solved the issue. Thanks :)

**Comment by Olgagr** [comment]
@dgreensp This is not working for me. I turned on this option, this is my `tsconfig.ts` file:

```{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "esModuleInterop": true,
    "target": "es5",
    "baseUrl": "./src",
    "paths": {
      "@angular/*": ["../node_modules/@angular/*"],
      "app/*": ["app/*"],
      "shared/*": ["app/shared/*"],
      "shared": ["app/shared"],
      "spec-helpers/*": ["app/spec-helpers/*"],
      "spec-helpers": ["app/spec-helpers"],
      "admin_app/*": ["app/admin_app/*"],
      "admin_app": ["app/admin_app"],
      "style_guides_app/*": ["app/style_guides_app/*"],
      "style_guides_app": ["app/style_guides_app"]
    },
    "typeRoots": ["node_modules/@types"],
    "types": ["node", "jasmine", "googlemaps"],
    "lib": ["es2018", "dom"]
  }
}```

I still get the error:

```node_modules/@types/quill/node_modules/quill-delta/dist/Delta.d.ts:1:8 - error TS1192: Module '"/home/admin/Documents/projects/project-angular/node_modules/@types/quill/node_modules/fast-diff/diff"' has no default export.```

**Comment by Hukutus** [comment]
I'm having the same problem, and esModuleInterop didn't work. Had to remove @types/quill for now because it caused build to fail.

**Comment by whyboris** [comment]
I'm on `Angular 9` with:
```
"quill": "1.3.7",
"@types/quill": "1.3.10",
```
Works fine, but when I update `@types/quill` to version `2.0.3` I get the above-mentioned-error 🤷‍♂️

**Comment by whyboris** [comment]
I was able to make the error go away by editing the `tsconfig.json` in two different ways:
-     `"esModuleInterop": true,` or
-     `"allowSyntheticDefaultImports": true,`

These go inside the `  "compilerOptions": { .. }`

**Comment by fdeguibert** [comment]
for anyone coming through this problem, the actual solution is not to mess with the compiler options but juste to be carefull with dependencies versions.
