### ISSUE TITLE
How to convert html to delta format using delta module?

### ISSUE THREAD

**Issue by sheeshmohsin** [quilljs/delta#6]
I have seen examples of conversion of delta to html format, but no where its explained to convert html to delta format. Is there anyway to do that?

**Comment by jhchen** [comment]
You can use the [construction APIs](https://github.com/quilljs/delta#construction-1) to create a Delta in general, but parsing, sanitizing and interpreting HTML is outside the scope of this project. You will have to use another third part for that in conjunction with the construction APIs.

**Comment by Toub** [comment]
What about using Clipboard.convert ?

https://github.com/quilljs/quill/blob/master/modules/clipboard.js

**Comment by aramk** [comment]
This seems to work:
```
quill.setContents(quill.clipboard.convert(html));
```

**Comment by sdhull** [comment]
I know this is an old issue but it strikes me as an odd oversight that Quill doesn't support this in any sort of documented way and the only way to do it is essentially a hack.

What is the recommended approach from Quill designers if I want to make some rich content editable more than once but also want to make the content renderable as simple HTML (as in the editor but just for display)?

AFAICT the easiest way to support this use-case is to store the content twice: once as Delta and once as HTML. Otherwise you're left rolling your own parser to convert HTML to Delta (if you store it as HTML) or Delta to HTML (for rendering outside an editor context).

Surely I'm missing something here?

**Comment by aramk** [comment]
I store it as HTML and delta as well so I can render without parsing each time. I think there should be a `setHtmlContents()` convenience method as well though.
